version: "3.7"

services:
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=evote
      - MYSQL_USER=evote
      - MYSQL_PASSWORD=123
      - TZ=Europe/Paris
    ports:
      - "3306:3306"
    hostname: database
    command: ["--event-scheduler=ON"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "evote", "-p123"]
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

